# Generated by Django 5.2.6 on 2025-09-29 06:12

from django.db import migrations

def criar_grupos_e_permissoes(apps, schema_editor):
    """
    Este script cria os grupos 'Veterinarios' e 'Recepcionistas'
    e atribui as permissões básicas para cada um.
    """
    # Usamos apps.get_model para pegar os modelos nesta fase da migração
    Group = apps.get_model('auth', 'Group')
    Permission = apps.get_model('auth', 'Permission')
    ContentType = apps.get_model('contenttypes', 'ContentType')

    # --- Permissões para o grupo RECEPCIONISTAS ---
    # Define os codenames das permissões que queremos dar
    permissoes_recepcionista = [
        'view_cliente', 'add_cliente', 'change_cliente',
        'view_animal', 'add_animal', 'change_animal',
        'view_consulta', 'add_consulta', 'change_consulta',
    ]
    # Filtra as permissões do banco de dados
    permissoes_recep_obj = Permission.objects.filter(codename__in=permissoes_recepcionista)
    
    # Cria o grupo e adiciona as permissões a ele
    grupo_recepcionistas, created = Group.objects.get_or_create(name='Recepcionistas')
    if created:
        grupo_recepcionistas.permissions.set(permissoes_recep_obj)
        print("Grupo 'Recepcionistas' criado e permissões atribuídas.")


    # --- Permissões para o grupo VETERINARIOS ---
    # Veterinários têm todas as permissões de recepcionistas e mais algumas
    permissoes_veterinario = permissoes_recepcionista
    permissoes_vet_obj = Permission.objects.filter(codename__in=permissoes_veterinario)

    # Cria o grupo e adiciona as permissões a ele
    grupo_veterinarios, created = Group.objects.get_or_create(name='Veterinarios')
    if created:
        grupo_veterinarios.permissions.set(permissoes_vet_obj)
        print("Grupo 'Veterinarios' criado e permissões atribuídas.")

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(criar_grupos_e_permissoes),
    ]
