# Generated by Django 5.2.6 on 2025-10-06 02:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_grupos_iniciais'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentoAnimal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text='Ex: Hemograma completo - Clínica X', max_length=100, verbose_name='Título/Descrição')),
                ('data_documento', models.DateField(verbose_name='Data do Documento')),
                ('arquivo', models.FileField(upload_to='documentos_animais/', verbose_name='Arquivo')),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='core.animal', verbose_name='Animal')),
            ],
            options={
                'verbose_name': 'Documento do Animal',
                'verbose_name_plural': 'Documentos dos Animais',
                'ordering': ['-data_documento'],
            },
        ),
    ]
